/*
 * This file was generated by the Gradle 'init' task.
 */
import org.gradle.api.tasks.SourceSetContainer
import org.gradle.language.jvm.tasks.ProcessResources
import org.gradle.api.tasks.testing.Test
plugins {
    `java-library`
    `maven-publish`
    id("io.github.goooler.shadow") version "8.1.8"
    id("pl.allegro.tech.build.axion-release") version "1.21.1"
}

scmVersion {
    tag {
        tag {
            prefix.set("v")
        }
        initialVersion({ _, _ -> "1.1.11"})
    }

    branchVersionCreator.putAll(mapOf("develop" to "simple"))
}

group = "de.janschuri"
version = scmVersion.version

repositories {
    mavenCentral()

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
        content {
            includeGroup("org.bstats")
            includeGroup("de.rapha149.signgui")
        }
    }

    maven {
        url = uri("https://www.iani.de/nexus/content/repositories/snapshots/")
        content {
            includeGroup("de.diddiz")
        }
    }
    maven {
        url = uri("https://maven.pkg.github.com/janschuri/lunaticlib")
        content {
            includeGroup("de.janschuri")
        }
        credentials {
            username = providers.gradleProperty("gpr.user").orNull
                ?: System.getenv("GITHUB_ACTOR")
            password = providers.gradleProperty("gpr.key").orNull
                ?: System.getenv("GITHUB_TOKEN")
        }
    }
}

dependencies {
    api(libs.de.janschuri.lunaticlib.paper)

    api(libs.de.rapha149.signgui)
    api(libs.com.jeff.media.custom.block.data)
    api(libs.fr.skytasul.glowingentities)
    api(libs.org.json.json)

    implementation(libs.org.bstats.bstats.bukkit)

    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.de.diddiz.logblock)
}


java.sourceCompatibility = JavaVersion.VERSION_21
java.targetCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks {
    build {
        dependsOn(shadowJar)
    }
    jar {
        enabled = false
    }
    shadowJar {
        archiveBaseName.set("LunaticStorage")
        archiveClassifier.set("")
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

data class MockBukkitSmokeTarget(
    val id: String,
    val artifact: String,
    val mockBukkitVersion: String,
    val junitVersion: String
)

val mockBukkitSmokeTargets = listOf(
    MockBukkitSmokeTarget("119", "MockBukkit-v1.19", "2.147.2", "5.9.2"),
    MockBukkitSmokeTarget("120", "MockBukkit-v1.20", "3.93.2", "5.10.3"),
    MockBukkitSmokeTarget("121", "MockBukkit-v1.21", "3.133.2", "5.11.2")
)

val sourceSets = extensions.getByType(SourceSetContainer::class.java)
val mainSourceSet = sourceSets.named("main").get()

val mockBukkitSmokeTasks = mockBukkitSmokeTargets.map { target ->
    val sourceSetName = "mockbukkit${target.id}Smoke"
    val sourceSet = sourceSets.create(sourceSetName) {
        java.srcDir("src/mockbukkitSmoke/java")
        resources.srcDir("src/mockbukkitSmoke/resources")

        compileClasspath += mainSourceSet.output + mainSourceSet.compileClasspath
        runtimeClasspath += output + mainSourceSet.output + mainSourceSet.runtimeClasspath
    }

    dependencies.add("${sourceSetName}Implementation", "org.junit.jupiter:junit-jupiter:${target.junitVersion}")
    dependencies.add("${sourceSetName}Implementation", "com.github.seeseemelk:${target.artifact}:${target.mockBukkitVersion}")

    tasks.register<Test>("${sourceSetName}Test") {
        description = "Runs the MockBukkit smoke test against ${target.artifact} ${target.mockBukkitVersion}."
        group = "verification"

        dependsOn(tasks.named(sourceSet.classesTaskName))

        if (target.id == "119") {
            val shadowJar = tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar")
            dependsOn(shadowJar)
            systemProperty(
                "lunaticstorage.test.pluginJar",
                shadowJar.flatMap { it.archiveFile }.get().asFile.absolutePath
            )
            jvmArgs("--add-opens=java.base/java.lang=ALL-UNNAMED")
        }

        testClassesDirs = sourceSet.output.classesDirs
        classpath = sourceSet.runtimeClasspath
        useJUnitPlatform()
    }
}

val mockBukkitSmokeAll = tasks.register("mockbukkitSmokeAll") {
    description = "Runs the MockBukkit smoke test against all configured MockBukkit version lines."
    group = "verification"
    dependsOn(mockBukkitSmokeTasks)
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()

    systemProperty("lunaticstorage.testMode", "true")

    testLogging {
        events("passed", "skipped", "failed")
    }
}

tasks.named<Test>("test") {
    dependsOn(mockBukkitSmokeAll)
}

tasks.named("check") {
    dependsOn(mockBukkitSmokeAll)
}

tasks.named<ProcessResources>("processResources") {
    val v = version.toString() // plain String, captured safely

    inputs.property("pluginVersion", v)
    filteringCharset = "UTF-8"

    filesMatching("plugin.yml") {
        expand(mapOf("version" to v))
    }
}
tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
    relocate("org.bstats", "de.janschuri.lunaticstorage.libs.bstats")
    relocate("com.jeff_media.customblockdata", "de.janschuri.lunaticstorage.libs.customblockdata")
    relocate("de.janschuri.lunaticlib", "de.janschuri.lunaticstorage.libs.lunaticlib")
}
