/*
 * This file was generated by the Gradle 'init' task.
 */
import org.gradle.language.jvm.tasks.ProcessResources
plugins {
    `java-library`
    `maven-publish`
    id("io.github.goooler.shadow") version "8.1.8"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://www.iani.de/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.de.janschuri.lunaticlib.paper)

    api(libs.de.rapha149.signgui)
    api(libs.com.jeff.media.custom.block.data)
    api(libs.fr.skytasul.glowingentities)
    api(libs.org.json.json)

    implementation(libs.org.bstats.bstats.bukkit)

    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.de.diddiz.logblock)
}

group = "de.janschuri"
version = "1.1.9-SNAPSHOT"
description = "LunaticStorage"
java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks {
    build {
        dependsOn(shadowJar)
    }
    jar {
        enabled = false
    }
    shadowJar {
        archiveBaseName.set("LunaticStorage")
        archiveClassifier.set("")
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.named<ProcessResources>("processResources") {
    val v = version.toString() // plain String, captured safely

    inputs.property("pluginVersion", v)
    filteringCharset = "UTF-8"

    filesMatching("plugin.yml") {
        expand(mapOf("version" to v))
    }
}
tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
    relocate("org.bstats", "de.janschuri.lunaticstorage.libs.bstats")
    relocate("com.jeff_media.customblockdata", "de.janschuri.lunaticstorage.libs.customblockdata")
    relocate("de.janschuri.lunaticlib", "de.janschuri.lunaticstorage.libs.lunaticlib")
}
